---
- name: Write a file with simulated update timestamp
  copy:
    dest: "{{ ansible_env.HOME }}/test_update_marker_controller_repo.txt"
    content: |
      Updated on: {{ ansible_date_time.iso8601 }}
    mode: '0644'
